export type RunStatus = 'completed' | 'failed' | 'running' | string;
export type RunGroupFilter = '' | 'summary' | 'repo_search' | 'planner' | 'chat' | 'other';
export type RunLogDeleteType = 'all' | Exclude<RunGroupFilter, ''>;
export type RunLogDeleteCriteria = {
    mode: 'count';
    type: RunLogDeleteType;
    count: number;
} | {
    mode: 'before_date';
    type: RunLogDeleteType;
    beforeDate: string;
};
export type RunLogDeletePreviewResponse = {
    ok: boolean;
    matchCount: number;
};
export type RunLogDeleteResponse = {
    ok: boolean;
    deletedCount: number;
    deletedRunIds: string[];
};
export type RunRecord = {
    id: string;
    kind: string;
    status: RunStatus;
    startedAtUtc: string | null;
    finishedAtUtc: string | null;
    title: string;
    model: string | null;
    backend: string | null;
    inputTokens: number | null;
    outputTokens: number | null;
    thinkingTokens: number | null;
    toolTokens?: number | null;
    promptCacheTokens: number | null;
    promptEvalTokens: number | null;
    promptEvalDurationMs?: number | null;
    generationDurationMs?: number | null;
    speculativeAcceptedTokens?: number | null;
    speculativeGeneratedTokens?: number | null;
    durationMs: number | null;
    rawPaths: Record<string, string | null>;
};
export type RunEvent = {
    kind: string;
    at: string | null;
    payload: unknown;
};
export type RunDetailResponse = {
    run: RunRecord;
    events: RunEvent[];
};
export type RunsResponse = {
    runs: RunRecord[];
    total: number;
};
export type MetricDay = {
    date: string;
    runs: number;
    inputTokens: number;
    outputTokens: number;
    thinkingTokens: number;
    toolTokens: number;
    promptCacheTokens: number;
    promptEvalTokens: number;
    cacheHitRate: number | null;
    speculativeAcceptedTokens: number;
    speculativeGeneratedTokens: number;
    acceptanceRate: number | null;
    successCount: number;
    failureCount: number;
    avgDurationMs: number;
};
export type TaskMetricDay = {
    date: string;
    taskKind: 'summary' | 'plan' | 'repo-search' | 'chat';
    runs: number;
    inputTokens: number;
    outputTokens: number;
    thinkingTokens: number;
    toolTokens: number;
    promptCacheTokens: number;
    promptEvalTokens: number;
    avgDurationMs: number;
};
export type ToolTypeStats = {
    calls: number;
    outputCharsTotal: number;
    outputTokensTotal: number;
    outputTokensEstimatedCount: number;
    lineReadCalls: number;
    lineReadLinesTotal: number;
    lineReadTokensTotal: number;
    finishRejections: number;
    semanticRepeatRejects: number;
    stagnationWarnings: number;
    forcedFinishFromStagnation: number;
    promptInsertedTokens: number;
    rawToolResultTokens: number;
    newEvidenceCalls: number;
    noNewEvidenceCalls: number;
    lineReadRecommendedLines?: number;
    lineReadAllowanceTokens?: number;
};
export type ToolStatsByTask = Record<'summary' | 'plan' | 'repo-search' | 'chat', Record<string, ToolTypeStats>>;
export type MetricsResponse = {
    days: MetricDay[];
    taskDays: TaskMetricDay[];
    toolStats: ToolStatsByTask;
};
export type IdleSummarySnapshot = {
    emittedAtUtc: string | null;
    completedRequestCount: number;
    inputCharactersTotal: number;
    outputCharactersTotal: number;
    inputTokensTotal: number;
    outputTokensTotal: number;
    inputOutputRatio: number | null;
    thinkingTokensTotal: number;
    toolTokensTotal: number;
    promptCacheTokensTotal: number;
    promptEvalTokensTotal: number;
    speculativeAcceptedTokensTotal?: number;
    speculativeGeneratedTokensTotal?: number;
    savedTokens: number;
    savedPercent: number | null;
    compressionRatio: number | null;
    requestDurationMsTotal: number;
    avgRequestMs: number | null;
    avgTokensPerSecond: number | null;
    taskTotals?: Record<string, unknown>;
    toolStats?: Record<string, unknown>;
    summaryText: string;
};
export type IdleSummaryResponse = {
    latest: IdleSummarySnapshot | null;
    snapshots: IdleSummarySnapshot[];
};
export type ChatMessage = {
    id: string;
    role: 'user' | 'assistant';
    content: string;
    inputTokensEstimate: number;
    outputTokensEstimate: number;
    thinkingTokens: number;
    inputTokensEstimated?: boolean;
    outputTokensEstimated?: boolean;
    thinkingTokensEstimated?: boolean;
    promptCacheTokens?: number | null;
    promptEvalTokens?: number | null;
    promptTokensPerSecond?: number | null;
    generationTokensPerSecond?: number | null;
    requestDurationMs?: number | null;
    promptEvalDurationMs?: number | null;
    generationDurationMs?: number | null;
    requestStartedAtUtc?: string | null;
    thinkingStartedAtUtc?: string | null;
    thinkingEndedAtUtc?: string | null;
    answerStartedAtUtc?: string | null;
    answerEndedAtUtc?: string | null;
    speculativeAcceptedTokens?: number | null;
    speculativeGeneratedTokens?: number | null;
    associatedToolTokens?: number;
    thinkingContent?: string;
    createdAtUtc: string;
    sourceRunId: string | null;
    compressedIntoSummary?: boolean;
};
export type HiddenToolContext = {
    id: string;
    content: string;
    tokenEstimate: number;
    sourceMessageId: string | null;
    createdAtUtc: string;
};
export type ChatSession = {
    id: string;
    title: string;
    model: string | null;
    contextWindowTokens: number;
    thinkingEnabled?: boolean;
    presetId?: string;
    mode?: 'chat' | 'plan' | 'repo-search';
    planRepoRoot?: string;
    condensedSummary: string;
    createdAtUtc: string;
    updatedAtUtc: string;
    messages: ChatMessage[];
    hiddenToolContexts?: HiddenToolContext[];
};
export type ContextUsage = {
    contextWindowTokens: number;
    usedTokens: number;
    chatUsedTokens: number;
    thinkingUsedTokens: number;
    toolUsedTokens: number;
    totalUsedTokens: number;
    remainingTokens: number;
    warnThresholdTokens: number;
    shouldCondense: boolean;
    estimatedTokenFallbackTokens?: number;
};
export type ChatSessionResponse = {
    session: ChatSession;
    contextUsage: ContextUsage;
};
export type ChatSessionsResponse = {
    sessions: ChatSession[];
};
export type DashboardPresetKind = 'summary' | 'chat' | 'plan' | 'repo-search';
export type DashboardPresetExecutionFamily = DashboardPresetKind;
export type DashboardPresetOperationMode = 'summary' | 'read-only' | 'full';
export type DashboardPresetSurface = 'cli' | 'web';
export type DashboardPresetToolName = 'find_text' | 'read_lines' | 'json_filter' | 'json_get' | 'repo_rg' | 'repo_read_file' | 'repo_list_files' | 'repo_git' | 'repo_select_object' | 'repo_where_object' | 'repo_sort_object' | 'repo_group_object' | 'repo_measure_object' | 'repo_foreach_object' | 'repo_format_table' | 'repo_format_list' | 'repo_out_string' | 'repo_convertto_json' | 'repo_convertfrom_json' | 'repo_get_unique' | 'repo_join_string';
export type DashboardOperationModeAllowedTools = Record<DashboardPresetOperationMode, DashboardPresetToolName[]>;
export type DashboardPreset = {
    id: string;
    label: string;
    description: string;
    presetKind: DashboardPresetKind;
    operationMode: DashboardPresetOperationMode;
    executionFamily: DashboardPresetExecutionFamily;
    promptPrefix: string;
    allowedTools: DashboardPresetToolName[];
    surfaces: DashboardPresetSurface[];
    useForSummary: boolean;
    builtin: boolean;
    deletable: boolean;
    includeAgentsMd: boolean;
    includeRepoFileListing: boolean;
    repoRootRequired: boolean;
    maxTurns: number | null;
};
export type DashboardManagedLlamaSpeculativeType = 'ngram-simple' | 'ngram-map-k' | 'ngram-map-k4v' | 'ngram-mod' | 'ngram-cache';
export type DashboardLlamaCppConfig = {
    BaseUrl: string;
    NumCtx: number;
    ModelPath: string | null;
    Temperature: number;
    TopP: number;
    TopK: number;
    MinP: number;
    PresencePenalty: number;
    RepetitionPenalty: number;
    MaxTokens: number;
    GpuLayers: number;
    Threads: number;
    NcpuMoe: number;
    FlashAttention: boolean;
    ParallelSlots: number;
    Reasoning: 'on' | 'off';
    ReasoningContent: boolean;
    PreserveThinking: boolean;
};
export type DashboardConfig = {
    Version: string;
    Backend: string;
    PolicyMode: string;
    RawLogRetention: boolean;
    PromptPrefix: string;
    OperationModeAllowedTools: DashboardOperationModeAllowedTools;
    Presets: DashboardPreset[];
    Model?: string;
    LlamaCpp: DashboardLlamaCppConfig;
    Runtime: {
        Model: string;
        LlamaCpp: DashboardLlamaCppConfig;
    };
    Thresholds: {
        MinCharactersForSummary: number;
        MinLinesForSummary: number;
    };
    Interactive: {
        Enabled: boolean;
        WrappedCommands: string[];
        IdleTimeoutMs: number;
        MaxTranscriptCharacters: number;
        TranscriptRetention: boolean;
    };
    Server: {
        LlamaCpp: {
            Model: string;
            ExecutablePath: string | null;
            BaseUrl: string;
            BindHost: string;
            Port: number;
            ModelPath: string | null;
            NumCtx: number;
            GpuLayers: number;
            Threads: number;
            NcpuMoe: number;
            FlashAttention: boolean;
            ParallelSlots: number;
            BatchSize: number;
            UBatchSize: number;
            CacheRam: number;
            KvCacheQuantization: 'f32' | 'f16' | 'bf16' | 'q8_0' | 'q4_0' | 'q4_1' | 'iq4_nl' | 'q5_0' | 'q5_1';
            MaxTokens: number;
            Temperature: number;
            TopP: number;
            TopK: number;
            MinP: number;
            PresencePenalty: number;
            RepetitionPenalty: number;
            Reasoning: 'on' | 'off';
            ReasoningContent: boolean;
            PreserveThinking: boolean;
            SpeculativeEnabled: boolean;
            SpeculativeType: DashboardManagedLlamaSpeculativeType;
            SpeculativeNgramSizeN: number;
            SpeculativeNgramSizeM: number;
            SpeculativeNgramMinHits: number;
            SpeculativeDraftMax: number;
            SpeculativeDraftMin: number;
            ReasoningBudget: number;
            ReasoningBudgetMessage: string;
            StartupTimeoutMs: number;
            HealthcheckTimeoutMs: number;
            HealthcheckIntervalMs: number;
            SleepIdleSeconds: number;
            VerboseLogging: boolean;
            Presets: DashboardManagedLlamaPreset[];
            ActivePresetId: string;
        };
    };
};
export type DashboardManagedLlamaPreset = {
    id: string;
    label: string;
    Model: string;
    ExecutablePath: string | null;
    BaseUrl: string;
    BindHost: string;
    Port: number;
    ModelPath: string | null;
    NumCtx: number;
    GpuLayers: number;
    Threads: number;
    NcpuMoe: number;
    FlashAttention: boolean;
    ParallelSlots: number;
    BatchSize: number;
    UBatchSize: number;
    CacheRam: number;
    KvCacheQuantization: 'f32' | 'f16' | 'bf16' | 'q8_0' | 'q4_0' | 'q4_1' | 'iq4_nl' | 'q5_0' | 'q5_1';
    MaxTokens: number;
    Temperature: number;
    TopP: number;
    TopK: number;
    MinP: number;
    PresencePenalty: number;
    RepetitionPenalty: number;
    Reasoning: 'on' | 'off';
    ReasoningContent: boolean;
    PreserveThinking: boolean;
    SpeculativeEnabled: boolean;
    SpeculativeType: DashboardManagedLlamaSpeculativeType;
    SpeculativeNgramSizeN: number;
    SpeculativeNgramSizeM: number;
    SpeculativeNgramMinHits: number;
    SpeculativeDraftMax: number;
    SpeculativeDraftMin: number;
    ReasoningBudget: number;
    ReasoningBudgetMessage: string;
    StartupTimeoutMs: number;
    HealthcheckTimeoutMs: number;
    HealthcheckIntervalMs: number;
    SleepIdleSeconds: number;
    VerboseLogging: boolean;
};
export type DashboardHealth = {
    ok: boolean;
    disableManagedLlamaStartup: boolean;
    statusPath: string;
    configPath: string;
    metricsPath: string;
    idleSummarySnapshotsPath: string;
    runtimeRoot: string;
};
export type ManagedFilePickerTarget = 'managed-llama-executable' | 'managed-llama-model';
export type ManagedFilePickerResponse = {
    ok: boolean;
    cancelled: boolean;
    path: string | null;
};
export type ManagedLlamaStartupFailure = {
    kind: 'gpu_memory_oom';
    requiredMiB: number;
    availableMiB: number;
};
export type RestartBackendResponse = {
    ok: boolean;
    restarted: boolean;
    error?: string;
    config?: DashboardConfig;
    startupFailure?: ManagedLlamaStartupFailure | null;
};
export type DashboardBenchmarkTaskKind = 'repo-search' | 'summary';
export type DashboardBenchmarkSessionStatus = 'running' | 'completed' | 'failed' | 'cancelled';
export type DashboardBenchmarkRestoreStatus = 'pending' | 'completed' | 'failed';
export type DashboardBenchmarkAttemptStatus = 'pending' | 'running' | 'completed' | 'failed' | 'cancelled' | 'skipped';
export type DashboardBenchmarkLogStreamKind = 'orchestrator' | 'attempt_stdout' | 'attempt_stderr' | 'managed_llama';
export type DashboardBenchmarkSortKey = 'completionSpeed' | 'generationTokensPerSecond' | 'acceptanceRate' | 'outputQualityScore' | 'toolUseQualityScore' | 'failureCount' | 'sampleCount';
export type DashboardBenchmarkQuestionPreset = {
    id: string;
    title: string;
    taskKind: DashboardBenchmarkTaskKind;
    prompt: string;
    enabled: boolean;
    seededKey?: string | null;
    createdAtUtc: string;
    updatedAtUtc: string;
};
export type DashboardBenchmarkSession = {
    id: string;
    status: DashboardBenchmarkSessionStatus;
    questionPresetCount: number;
    caseCount: number;
    repetitions: number;
    currentCaseIndex: number | null;
    currentPromptIndex: number | null;
    currentRepeatIndex: number | null;
    restoreStatus: DashboardBenchmarkRestoreStatus;
    restoreError: string | null;
    originalConfigJson: string;
    startedAtUtc: string;
    completedAtUtc: string | null;
    updatedAtUtc: string;
};
export type DashboardBenchmarkCase = {
    id: string;
    sessionId: string;
    caseIndex: number;
    label: string;
    managedPresetId: string;
    managedPresetLabel: string;
    managedPreset: Record<string, unknown>;
    specOverride: Record<string, unknown>;
    createdAtUtc: string;
};
export type DashboardBenchmarkAttempt = {
    id: string;
    sessionId: string;
    caseId: string;
    questionPresetId: string;
    taskKind: DashboardBenchmarkTaskKind;
    promptTitle: string;
    prompt: string;
    caseLabel: string;
    managedPresetId: string;
    managedPresetLabel: string;
    caseIndex: number;
    promptIndex: number;
    repeatIndex: number;
    status: DashboardBenchmarkAttemptStatus;
    outputText: string | null;
    error: string | null;
    runId: string | null;
    managedRunId: string | null;
    durationMs: number | null;
    promptTokensPerSecond: number | null;
    generationTokensPerSecond: number | null;
    acceptanceRate: number | null;
    outputTokens: number | null;
    thinkingTokens: number | null;
    speculativeAcceptedTokens: number | null;
    speculativeGeneratedTokens: number | null;
    outputQualityScore: number | null;
    toolUseQualityScore: number | null;
    reviewNotes: string | null;
    reviewedBy: string | null;
    reviewedAtUtc: string | null;
    startedAtUtc: string | null;
    completedAtUtc: string | null;
    updatedAtUtc: string;
};
export type DashboardBenchmarkSessionDetail = {
    session: DashboardBenchmarkSession;
    cases: DashboardBenchmarkCase[];
    attempts: DashboardBenchmarkAttempt[];
};
export type DashboardBenchmarkQuestionPresetsResponse = {
    presets: DashboardBenchmarkQuestionPreset[];
};
export type DashboardBenchmarkSessionsResponse = {
    sessions: DashboardBenchmarkSession[];
};
export type DashboardBenchmarkStartRequest = {
    questionPresetIds: string[];
    managedPresetIds: string[];
    repetitions: number;
    specOverrides: Array<Record<string, unknown>>;
};
export type DashboardBenchmarkGradeRequest = {
    outputQualityScore: number | null;
    toolUseQualityScore: number | null;
    reviewNotes: string | null;
    reviewedBy: string;
};
