import {
  SIFTKIT_VERSION,
  SIFT_DEFAULT_ENGINE_BASE_URL,
  SIFT_DEFAULT_EXL3_RECURRENT_CACHE_RAM,
  SIFT_DEFAULT_ENGINE_CACHE_RAM,
  SIFT_DEFAULT_ENGINE_KV_CACHE_QUANTIZATION,
  SIFT_DEFAULT_ENGINE_REASONING_BUDGET,
  SIFT_DEFAULT_ENGINE_REASONING_BUDGET_MESSAGE,
  SIFT_DEFAULT_ENGINE_SLEEP_IDLE_SECONDS,
  SIFT_DEFAULT_ENGINE_UBATCH_SIZE,
  SIFT_DEFAULT_VISION_ENABLED,
  SIFT_DEFAULT_VISION_OFFLOAD,
  SIFT_DEFAULT_VISION_IMAGE_RETENTION,
  SIFT_DEFAULT_VISION_MAX_IMAGE_PIXELS,
  SIFT_DEFAULT_NUM_CTX,
  SIFT_DEFAULT_PROMPT_PREFIX,
} from './constants.js';
import { DEFAULT_REASONING_EFFORT } from '@siftkit/contracts';
import { initializeRuntime } from './paths.js';
import { PresetCatalog } from '../preset-catalog.js';
import { getDefaultOperationModeAllowedTools } from '../presets.js';
import type { AssistantConfig, ModelRuntimePreset, SiftConfig } from './types.js';

export const DEFAULT_ASSISTANT_CONFIG: AssistantConfig = {
  Enabled: false,
  Owner: { Id: 'own_local', DisplayName: 'Local user' },
  Memory: {
    Tier1: { MaxTokens: 10_000, TargetTokens: 3_500 },
    Tier2: { MaxDocuments: 25, MaxTokensPerDocument: 50_000, TargetTokensPerDocument: 8_000 },
    Tier3: { MaxDocuments: 500, MaxTokensPerDocument: 10_000, TargetTokensPerDocument: 2_500 },
  },
  Retrieval: {
    MaxContextTokens: 1_200,
    MaxHops: 2,
    MaxSeedNodes: 12,
    MaxNodes: 80,
    MaxAssertions: 160,
    MaxFanoutPerNodePredicate: 20,
  },
  Questions: {
    Enabled: true,
    MaxPerDay: 1,
    MaxPerWeek: 3,
    MinimumHoursBetweenQuestions: 20,
    AllowedLocalTimeStart: '18:00',
    AllowedLocalTimeEnd: '21:30',
    DismissedCooldownDays: 7,
    UnansweredExpiryDays: 7,
    SuppressDuringFullscreen: true,
    SuppressDuringDoNotDisturb: true,
    ActiveInputSuppressionSeconds: 120,
  },
  Observation: {
    ActivityMetadataEnabled: true,
    ScreenshotsEnabled: false,
    FixedCadenceSeconds: 30,
    WindowChangeCapture: false,
    MinimumForegroundDwellSeconds: 5,
    DuplicateSimilarityPercent: 92,
    CaptureScope: 'foreground_window',
    CaptureOnlyWhileActive: true,
    SkipFullscreen: true,
    SkipWhileLocked: true,
    RawRetentionHours: 72,
    RawStorageLimitGb: 5,
    AccessibilityExtractionEnabled: true,
    OcrFallbackEnabled: true,
    ProcessDenyList: [],
    TitleDenyPatterns: [],
    StartOnSignIn: false,
  },
  Retention: { OcrTextDays: 7, UnpromotedObservationDays: 90, RejectedCandidateDays: 30 },
  Background: {
    IdleSecondsBeforeProcessing: 180,
    MaxJobsPerIdleSession: -1,
    MaxGpuMinutesPerDay: -1,
    MinimumBatteryPercent: 50,
    AllowOnBattery: false,
    JobPriorities: {
      ConversationIngestion: 800,
      QuestionAnswerIngestion: 850,
      QuestionPlanning: 600,
      CandidateConsolidation: 400,
      ImageExtraction: 350,
      CaptureRetention: 900,
      ProjectionMaintenance: 300,
    },
  },
  PrivateMode: { Active: false, ExpiresAtUtc: null },
  Mobile: { Enabled: false },
  KeyCustody: 'file',
};

export function getDefaultConfigObject(): SiftConfig {
  const runtimePaths = initializeRuntime();
  // The default preset names no model: the user must pick a model directory under the EXL3
  // ModelRoot before the first launch, and the server reports that as a configuration error.
  const defaultModelPreset: ModelRuntimePreset = {
    id: 'default',
    label: 'Default',
    Backend: 'exl3',
    Model: null,
    ExternalServerEnabled: false,
    BaseUrl: SIFT_DEFAULT_ENGINE_BASE_URL,
    ModelPath: null,
    NumCtx: SIFT_DEFAULT_NUM_CTX,
    ParallelSlots: 1,
    UBatchSize: SIFT_DEFAULT_ENGINE_UBATCH_SIZE,
    CacheRam: SIFT_DEFAULT_ENGINE_CACHE_RAM,
    CacheRecurrentRam: SIFT_DEFAULT_EXL3_RECURRENT_CACHE_RAM,
    KvCacheQuantization: SIFT_DEFAULT_ENGINE_KV_CACHE_QUANTIZATION,
    MaxTokens: 15_000,
    Temperature: 0.7,
    TopP: 0.8,
    TopK: 20,
    MinP: 0.0,
    PresencePenalty: 1.5,
    RepetitionPenalty: 1.0,
    Reasoning: 'off' as const,
    ReasoningEffort: DEFAULT_REASONING_EFFORT,
    ReasoningContent: false,
    PreserveThinking: false,
    MaintainPerStepThinking: false,
    SpeculativeEnabled: false,
    SpeculativeDraftMax: 16,
    SpeculativeDynamic: true,
    ReasoningBudget: SIFT_DEFAULT_ENGINE_REASONING_BUDGET,
    ReasoningBudgetMessage: SIFT_DEFAULT_ENGINE_REASONING_BUDGET_MESSAGE,
    StartupTimeoutMs: 600_000,
    HealthcheckTimeoutMs: 2_000,
    HealthcheckIntervalMs: 1_000,
    SleepIdleSeconds: SIFT_DEFAULT_ENGINE_SLEEP_IDLE_SECONDS,
    IdleAction: 'unload',
    VisionEnabled: SIFT_DEFAULT_VISION_ENABLED,
    VisionOffload: SIFT_DEFAULT_VISION_OFFLOAD,
    VisionImageRetention: SIFT_DEFAULT_VISION_IMAGE_RETENTION,
    VisionMaxImagePixels: SIFT_DEFAULT_VISION_MAX_IMAGE_PIXELS,
  };
  return {
    Version: SIFTKIT_VERSION,
    PolicyMode: 'conservative',
    RawLogRetention: true,
    ExpandReads: true,
    PromptPrefix: SIFT_DEFAULT_PROMPT_PREFIX,
    Inference: {
      Thinking: { Enabled: false, Preserve: false },
    },
    Runtime: {
      Engine: {},
    },
    Thresholds: {
      MinCharactersForSummary: 500,
      MinLinesForSummary: 16,
    },
    Interactive: {
      Enabled: true,
      WrappedCommands: ['git', 'less', 'vim', 'sqlite3'],
      IdleTimeoutMs: 900_000,
      MaxTranscriptCharacters: 60_000,
      TranscriptRetention: true,
    },
    Server: {
      ModelPresets: {
        Presets: [defaultModelPreset],
        ActivePresetId: defaultModelPreset.id,
      },
      Engines: {
        Exl3: {
          Managed: true,
          WorkingDirectory: 'C:\\Users\\denys\\Documents\\GitHub\\TabbyAPI',
          PythonPath: 'C:\\envs\\rl313-turbo\\Scripts\\python.exe',
          Entrypoint: 'main.py',
          ModelRoot: 'D:\\personal\\models\\elx3',
          AdminApiKey: '',
          ShutdownTimeoutMs: 30_000,
        },
      },
    },
    OperationModeAllowedTools: getDefaultOperationModeAllowedTools(),
    Presets: PresetCatalog.createDefault().list(),
    WebSearch: {
      EnabledDefault: true,
      Providers: {
        tavily: { Enabled: false, ApiKey: '' },
        firecrawl: { Enabled: false, ApiKey: '' },
      },
      ProviderOrder: ['tavily', 'firecrawl'],
      ResultCount: 5,
      FetchMaxPages: 3,
      TimeoutMs: 15000,
      FetchMaxCharacters: 12000,
    },
    Assistant: DEFAULT_ASSISTANT_CONFIG,
    Paths: runtimePaths,
  };
}
