import {
  SIFTKIT_VERSION,
  SIFT_DEFAULT_LLAMA_BASE_URL,
  SIFT_DEFAULT_LLAMA_BATCH_SIZE,
  SIFT_DEFAULT_LLAMA_BIND_HOST,
  SIFT_DEFAULT_LLAMA_CACHE_RAM,
  SIFT_DEFAULT_LLAMA_KV_CACHE_QUANTIZATION,
  SIFT_DEFAULT_LLAMA_GPU_LAYERS,
  SIFT_DEFAULT_LLAMA_MODEL,
  SIFT_DEFAULT_LLAMA_PORT,
  SIFT_DEFAULT_LLAMA_REASONING_BUDGET,
  SIFT_DEFAULT_LLAMA_REASONING_BUDGET_MESSAGE,
  SIFT_DEFAULT_LLAMA_SLEEP_IDLE_SECONDS,
  SIFT_DEFAULT_LLAMA_UBATCH_SIZE,
  SIFT_DEFAULT_NUM_CTX,
  SIFT_DEFAULT_PROMPT_PREFIX,
} from './constants.js';
import { initializeRuntime } from './paths.js';
import { getDefaultOperationModeAllowedTools, normalizePresets } from '../presets.js';
import type { ModelRuntimePreset, SiftConfig } from './types.js';

export function getDefaultConfigObject(): SiftConfig {
  const runtimePaths = initializeRuntime();
  const defaultModelPreset: ModelRuntimePreset = {
    id: 'default',
    label: 'Default',
    Backend: 'llama',
    Model: SIFT_DEFAULT_LLAMA_MODEL,
    ExternalServerEnabled: false,
    ExecutablePath: null,
    BaseUrl: SIFT_DEFAULT_LLAMA_BASE_URL,
    BindHost: SIFT_DEFAULT_LLAMA_BIND_HOST,
    Port: SIFT_DEFAULT_LLAMA_PORT,
    ModelPath: null,
    NumCtx: SIFT_DEFAULT_NUM_CTX,
    GpuLayers: SIFT_DEFAULT_LLAMA_GPU_LAYERS,
    Threads: -1,
    NcpuMoe: 0,
    FlashAttention: true,
    ParallelSlots: 1,
    BatchSize: SIFT_DEFAULT_LLAMA_BATCH_SIZE,
    UBatchSize: SIFT_DEFAULT_LLAMA_UBATCH_SIZE,
    CacheRam: SIFT_DEFAULT_LLAMA_CACHE_RAM,
    KvCacheQuantization: SIFT_DEFAULT_LLAMA_KV_CACHE_QUANTIZATION,
    MaxTokens: 15_000,
    Temperature: 0.7,
    TopP: 0.8,
    TopK: 20,
    MinP: 0.0,
    PresencePenalty: 1.5,
    RepetitionPenalty: 1.0,
    Reasoning: 'off' as const,
    ReasoningContent: false,
    PreserveThinking: false,
    MaintainPerStepThinking: false,
    SpeculativeEnabled: false,
    SpeculativeType: 'ngram-map-k',
    SpeculativeMtpEnabled: false,
    SpeculativeNgramSizeN: 8,
    SpeculativeNgramSizeM: 16,
    SpeculativeNgramMinHits: 2,
    SpeculativeNgramModNMatch: 24,
    SpeculativeNgramModNMin: 4,
    SpeculativeNgramModNMax: 16,
    SpeculativeDraftMax: 16,
    SpeculativeDraftMin: 4,
    ReasoningBudget: SIFT_DEFAULT_LLAMA_REASONING_BUDGET,
    ReasoningBudgetMessage: SIFT_DEFAULT_LLAMA_REASONING_BUDGET_MESSAGE,
    StartupTimeoutMs: 600_000,
    HealthcheckTimeoutMs: 2_000,
    HealthcheckIntervalMs: 1_000,
    SleepIdleSeconds: SIFT_DEFAULT_LLAMA_SLEEP_IDLE_SECONDS,
    VerboseLogging: false,
  };
  return {
    Version: SIFTKIT_VERSION,
    PolicyMode: 'conservative',
    RawLogRetention: true,
    IncludeAgentsMd: true,
    IncludeRepoFileListing: true,
    ExpandReads: true,
    PromptPrefix: SIFT_DEFAULT_PROMPT_PREFIX,
    Inference: {
      Thinking: { Enabled: false, Preserve: false },
    },
    Runtime: {
      LlamaCpp: {},
    },
    Thresholds: {
      MinCharactersForSummary: 500,
      MinLinesForSummary: 16,
    },
    Interactive: {
      Enabled: true,
      WrappedCommands: ['git', 'less', 'vim', 'sqlite3'],
      IdleTimeoutMs: 900_000,
      MaxTranscriptCharacters: 60_000,
      TranscriptRetention: true,
    },
    Server: {
      ModelPresets: {
        Presets: [defaultModelPreset],
        ActivePresetId: defaultModelPreset.id,
      },
      Engines: {
        Exl3: {
          Managed: true,
          WorkingDirectory: 'C:\\Users\\denys\\Documents\\GitHub\\TabbyAPI',
          PythonPath: 'C:\\envs\\rl310\\Scripts\\python.exe',
          Entrypoint: 'main.py',
          ModelRoot: 'D:\\personal\\models\\elx3',
          AdminApiKey: '',
          ShutdownTimeoutMs: 30_000,
        },
      },
    },
    OperationModeAllowedTools: getDefaultOperationModeAllowedTools(),
    Presets: normalizePresets([]),
    WebSearch: {
      EnabledDefault: true,
      Providers: {
        tavily: { Enabled: false, ApiKey: '' },
        firecrawl: { Enabled: false, ApiKey: '' },
      },
      ProviderOrder: ['tavily', 'firecrawl'],
      ResultCount: 5,
      FetchMaxPages: 3,
      TimeoutMs: 15000,
      FetchMaxCharacters: 12000,
    },
    Paths: runtimePaths,
  };
}
