import {
  SIFTKIT_VERSION,
  SIFT_DEFAULT_LLAMA_BASE_URL,
  SIFT_DEFAULT_LLAMA_BATCH_SIZE,
  SIFT_DEFAULT_LLAMA_BIND_HOST,
  SIFT_DEFAULT_LLAMA_CACHE_RAM,
  SIFT_DEFAULT_LLAMA_KV_CACHE_QUANTIZATION,
  SIFT_DEFAULT_LLAMA_GPU_LAYERS,
  SIFT_DEFAULT_LLAMA_MODEL,
  SIFT_DEFAULT_LLAMA_PORT,
  SIFT_DEFAULT_LLAMA_REASONING_BUDGET,
  SIFT_DEFAULT_LLAMA_REASONING_BUDGET_MESSAGE,
  SIFT_DEFAULT_LLAMA_UBATCH_SIZE,
  SIFT_DEFAULT_NUM_CTX,
  SIFT_DEFAULT_PROMPT_PREFIX,
} from './constants.js';
import { initializeRuntime } from './paths.js';
import type { ServerManagedLlamaPreset, SiftConfig } from './types.js';

export function getDefaultConfigObject(): SiftConfig {
  const runtimePaths = initializeRuntime();
  const defaultManagedLlamaPreset: ServerManagedLlamaPreset = {
    id: 'default',
    label: 'Default',
    ExecutablePath: null,
    BaseUrl: SIFT_DEFAULT_LLAMA_BASE_URL,
    BindHost: SIFT_DEFAULT_LLAMA_BIND_HOST,
    Port: SIFT_DEFAULT_LLAMA_PORT,
    ModelPath: null,
    NumCtx: SIFT_DEFAULT_NUM_CTX,
    GpuLayers: SIFT_DEFAULT_LLAMA_GPU_LAYERS,
    Threads: -1,
    NcpuMoe: 0,
    FlashAttention: true,
    ParallelSlots: 1,
    BatchSize: SIFT_DEFAULT_LLAMA_BATCH_SIZE,
    UBatchSize: SIFT_DEFAULT_LLAMA_UBATCH_SIZE,
    CacheRam: SIFT_DEFAULT_LLAMA_CACHE_RAM,
    KvCacheQuantization: SIFT_DEFAULT_LLAMA_KV_CACHE_QUANTIZATION,
    MaxTokens: 15_000,
    Temperature: 0.7,
    TopP: 0.8,
    TopK: 20,
    MinP: 0.0,
    PresencePenalty: 1.5,
    RepetitionPenalty: 1.0,
    Reasoning: 'off' as const,
    ReasoningContent: false,
    PreserveThinking: false,
    ReasoningBudget: SIFT_DEFAULT_LLAMA_REASONING_BUDGET,
    ReasoningBudgetMessage: SIFT_DEFAULT_LLAMA_REASONING_BUDGET_MESSAGE,
    StartupTimeoutMs: 600_000,
    HealthcheckTimeoutMs: 2_000,
    HealthcheckIntervalMs: 1_000,
    VerboseLogging: false,
  };
  return {
    Version: SIFTKIT_VERSION,
    Backend: 'llama.cpp',
    PolicyMode: 'conservative',
    RawLogRetention: true,
    PromptPrefix: SIFT_DEFAULT_PROMPT_PREFIX,
    LlamaCpp: {
      BaseUrl: SIFT_DEFAULT_LLAMA_BASE_URL,
      NumCtx: SIFT_DEFAULT_NUM_CTX,
      ModelPath: null,
      Temperature: 0.7,
      TopP: 0.8,
      TopK: 20,
      MinP: 0.0,
      PresencePenalty: 1.5,
      RepetitionPenalty: 1.0,
      MaxTokens: 15_000,
      GpuLayers: SIFT_DEFAULT_LLAMA_GPU_LAYERS,
      Threads: -1,
      NcpuMoe: 0,
      FlashAttention: true,
      ParallelSlots: 1,
      Reasoning: 'off',
    },
    Runtime: {
      Model: SIFT_DEFAULT_LLAMA_MODEL,
      LlamaCpp: {
        BaseUrl: SIFT_DEFAULT_LLAMA_BASE_URL,
        NumCtx: SIFT_DEFAULT_NUM_CTX,
        ModelPath: null,
        Temperature: 0.7,
        TopP: 0.8,
        TopK: 20,
        MinP: 0.0,
        PresencePenalty: 1.5,
        RepetitionPenalty: 1.0,
        MaxTokens: 15_000,
        GpuLayers: SIFT_DEFAULT_LLAMA_GPU_LAYERS,
        Threads: -1,
        NcpuMoe: 0,
        FlashAttention: true,
        ParallelSlots: 1,
        Reasoning: 'off',
      },
    },
    Thresholds: {
      MinCharactersForSummary: 500,
      MinLinesForSummary: 16,
    },
    Interactive: {
      Enabled: true,
      WrappedCommands: ['git', 'less', 'vim', 'sqlite3'],
      IdleTimeoutMs: 900_000,
      MaxTranscriptCharacters: 60_000,
      TranscriptRetention: true,
    },
    Server: {
      LlamaCpp: {
        ...defaultManagedLlamaPreset,
        Presets: [defaultManagedLlamaPreset],
        ActivePresetId: defaultManagedLlamaPreset.id,
      },
    },
    Paths: runtimePaths,
  };
}
