export type PresetKind = 'summary' | 'chat' | 'plan' | 'repo-search';
export type PresetExecutionFamily = PresetKind;
export type PresetOperationMode = 'summary' | 'read-only' | 'full';
export type PresetSurface = 'cli' | 'web';
export declare const REPO_SEARCH_TOOLS: readonly ["repo_rg", "repo_read_file", "repo_list_files", "repo_git", "repo_select_object", "repo_where_object", "repo_sort_object", "repo_group_object", "repo_measure_object", "repo_foreach_object", "repo_format_table", "repo_format_list", "repo_out_string", "repo_convertto_json", "repo_convertfrom_json", "repo_get_unique", "repo_join_string"];
export declare const WEB_RESEARCH_TOOLS: readonly ["web_search", "web_fetch"];
declare const PRESET_TOOL_NAMES: readonly ["find_text", "read_lines", "json_filter", "json_get", "repo_rg", "repo_read_file", "repo_list_files", "repo_git", "repo_select_object", "repo_where_object", "repo_sort_object", "repo_group_object", "repo_measure_object", "repo_foreach_object", "repo_format_table", "repo_format_list", "repo_out_string", "repo_convertto_json", "repo_convertfrom_json", "repo_get_unique", "repo_join_string", "web_search", "web_fetch"];
export type PresetToolName = (typeof PRESET_TOOL_NAMES)[number];
export type OperationModeAllowedTools = Record<PresetOperationMode, PresetToolName[]>;
export type SiftPreset = {
    id: string;
    label: string;
    description: string;
    presetKind: PresetKind;
    operationMode: PresetOperationMode;
    executionFamily: PresetExecutionFamily;
    promptPrefix: string;
    allowedTools: PresetToolName[];
    surfaces: PresetSurface[];
    useForSummary: boolean;
    builtin: boolean;
    deletable: boolean;
    includeAgentsMd: boolean;
    includeRepoFileListing: boolean;
    repoRootRequired: boolean;
    maxTurns: number | null;
};
export declare function getDefaultOperationModeAllowedTools(): OperationModeAllowedTools;
export declare function normalizeOperationModeAllowedTools(input: unknown): OperationModeAllowedTools;
export declare function resolvePresetAllowedTools(preset: Pick<SiftPreset, 'allowedTools' | 'operationMode'>, operationModeAllowedTools: OperationModeAllowedTools): PresetToolName[];
export declare function getBuiltinPresets(): SiftPreset[];
export declare function normalizePresets(input: unknown): SiftPreset[];
export declare function findPresetById(presets: readonly SiftPreset[], presetId: unknown): SiftPreset | null;
export declare function getConfigPresets(config: unknown): SiftPreset[];
export declare function getPresetsForSurface(presets: readonly SiftPreset[], surface: PresetSurface): SiftPreset[];
export declare function resolveSummaryPreset(presets: readonly SiftPreset[]): SiftPreset;
export declare function getPresetExecutionFamily(presetId: unknown, presets: readonly SiftPreset[]): PresetExecutionFamily;
export declare function getPresetKind(presetId: unknown, presets: readonly SiftPreset[]): PresetKind;
export declare function getPresetExecutionOperationMode(presetId: unknown, presets: readonly SiftPreset[]): PresetOperationMode;
export declare function mapLegacyModeToPresetId(mode: unknown): string;
export declare function mapPresetIdToLegacyMode(presetId: unknown, presets?: readonly SiftPreset[]): 'chat' | 'plan' | 'repo-search';
export declare function getPresetSurfaceOptions(): PresetSurface[];
export declare function isBuiltinPresetId(value: unknown): boolean;
export {};
